apiVersion: v1
kind: Namespace
metadata:
  name: mendix
  labels:
    app.kubernetes.io/managed-by: helm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mendix-app
  namespace: mendix
  annotations:
    azure.workload.identity/client-id: {{ .Values.workloadIdentity.clientId | quote }}
    azure.workload.identity/tenant-id: {{ .Values.workloadIdentity.tenantId | quote }}
  labels:
    azure.workload.identity/use: "true"
