apiVersion: v1
kind: Service
metadata:
  name: mendix-app-lb
  namespace: mendix
spec:
  type: LoadBalancer
  selector:
    app: mendix-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
