replicaCount: 1
image:
  repository: acromnixl7yf2e.azurecr.io/omnix-mendix
  tag: mx-v3
  pullPolicy: IfNotPresent
placeholder:
  enabled: false
  image: nginxdemos/hello:plain-text
containerPort: 8080
workloadIdentity:
  clientId: 3b9adfd0-dfe3-4b49-9404-ecc62b77bb32
  tenantId: f18bd124-cda1-42b5-929a-51779df22782
keyVault:
  name: kv-omnix-prod-73k2
  secrets:
    - MendixDatabaseConnection
    - MendixDatabasePassword
    - MendixStorageAccountKey
fileShare:
  enabled: false
resources:
  requests:
    cpu: 200m
    memory: 1Gi
  limits:
    cpu: 1500m
    memory: 2Gi
autoscaling:
  enabled: false
gateway:
  enabled: false
