replicaCount: 1

image:
  repository: acromnixl7yf2e.azurecr.io/omnix-mendix
  tag: mx-v3
  pullPolicy: IfNotPresent

placeholder:
  enabled: false
  image: nginxdemos/hello:plain-text

containerPort: 8080

workloadIdentity:
  clientId: d63e470f-9f81-4d58-8c19-ba5d04b9fd6a
  tenantId: f18bd124-cda1-42b5-929a-51779df22782

keyVault:
  name: kv-omnix-dev-9hho
  secrets:
    - MendixDatabaseConnection
    - MendixDatabasePassword
    - MendixStorageAccountKey

fileShare:
  enabled: false

resources:
  requests:
    cpu: 200m
    memory: 1Gi
  limits:
    cpu: 1500m
    memory: 2Gi

autoscaling:
  enabled: false

gateway:
  enabled: false
